name: Build Ruby Distroless Images to GHCR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: "linux/amd64"
            ruby_version: "2.5.9"
            ruby_major_minor: "2.5"
          - platform: "linux/amd64"
            ruby_version: "2.6.10"
            ruby_major_minor: "2.6"
          - platform: "linux/amd64"
            ruby_version: "2.7.8"
            ruby_major_minor: "2.7"
          - platform: "linux/amd64"
            ruby_version: "3.0.7"
            ruby_major_minor: "3.0"
          - platform: "linux/amd64"
            ruby_version: "3.1.6"
            ruby_major_minor: "3.1"
          - platform: "linux/amd64"
            ruby_version: "3.2.7"
            ruby_major_minor: "3.2"
          - platform: "linux/amd64"
            ruby_version: "3.3.7"
            ruby_major_minor: "3.3"
          - platform: "linux/amd64"
            ruby_version: "3.4.2"
            ruby_major_minor: "3.4"
          # arm64
          - platform: "linux/arm64"
            ruby_version: "2.5.9"
            ruby_major_minor: "2.5"
          - platform: "linux/arm64"
            ruby_version: "2.6.10"
            ruby_major_minor: "2.6"
          - platform: "linux/arm64"
            ruby_version: "2.7.8"
            ruby_major_minor: "2.7"
          - platform: "linux/arm64"
            ruby_version: "3.0.7"
            ruby_major_minor: "3.0"
          - platform: "linux/arm64"
            ruby_version: "3.1.6"
            ruby_major_minor: "3.1"
          - platform: "linux/arm64"
            ruby_version: "3.2.7"
            ruby_major_minor: "3.2"
          - platform: "linux/arm64"
            ruby_version: "3.3.7"
            ruby_major_minor: "3.3"
          - platform: "linux/arm64"
            ruby_version: "3.4.2"
            ruby_major_minor: "3.4"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set platform-specific environment variables
        run: |
          if [ "${{ matrix.platform }}" == "linux/arm64" ]; then
            echo "LIB_Z_PATH=/lib/aarch64-linux-gnu/libz.so.1" >> $GITHUB_ENV
            echo "LIB_GMP_PATH=/usr/lib/aarch64-linux-gnu/libgmp.so.10" >> $GITHUB_ENV
            echo "LIB_CRYPT_PATH=/lib/aarch64-linux-gnu/libcrypt.so.1" >> $GITHUB_ENV
            echo "LIB_GCC_PATH=/lib/aarch64-linux-gnu/libgcc_s.so.1" >> $GITHUB_ENV
            echo "LD_LIB_PATH=/usr/local/lib:/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu" >> $GITHUB_ENV
          else
            echo "LIB_Z_PATH=/lib/x86_64-linux-gnu/libz.so.1" >> $GITHUB_ENV
            echo "LIB_GMP_PATH=/usr/lib/x86_64-linux-gnu/libgmp.so.10" >> $GITHUB_ENV
            echo "LIB_CRYPT_PATH=/lib/x86_64-linux-gnu/libcrypt.so.1" >> $GITHUB_ENV
            echo "LIB_GCC_PATH=/lib/x86_64-linux-gnu/" >> $GITHUB_ENV
            echo "LD_LIB_PATH=/usr/local/lib:/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          fi

      - name: Convert platform tag
        id: convert
        run: |
          TAG_PLATFORM="${{ matrix.platform }}"
          TAG_PLATFORM=${TAG_PLATFORM/linux\//}
          echo "tag_platform=$TAG_PLATFORM" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/junminhong/ruby-distroless:${{ matrix.ruby_version }}-${{ steps.convert.outputs.tag_platform }}
          build-args: |
            RUBY_VERSION=${{ matrix.ruby_version }}
            RUBY_MAJOR_MINOR=${{ matrix.ruby_major_minor }}
            LIB_Z_PATH=${{ env.LIB_Z_PATH }}
            LIB_GMP_PATH=${{ env.LIB_GMP_PATH }}
            LIB_CRYPT_PATH=${{ env.LIB_CRYPT_PATH }}
            LIB_GCC_PATH=${{ env.LIB_GCC_PATH }}
            LD_LIB_PATH=${{ env.LD_LIB_PATH }}
          push: true
