name: Build Ruby Distroless Images to GHCR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: "linux/amd64"
            ruby_version: "2.6.10"
            ruby_major_minor: "2.6"
          - platform: "linux/amd64"
            ruby_version: "2.7.8"
            ruby_major_minor: "2.7"
          - platform: "linux/amd64"
            ruby_version: "3.0.7"
            ruby_major_minor: "3.0"
          - platform: "linux/amd64"
            ruby_version: "3.1.6"
            ruby_major_minor: "3.1"
          - platform: "linux/amd64"
            ruby_version: "3.2.7"
            ruby_major_minor: "3.2"
          - platform: "linux/amd64"
            ruby_version: "3.3.7"
            ruby_major_minor: "3.3"
          - platform: "linux/amd64"
            ruby_version: "3.4.2"
            ruby_major_minor: "3.4"
          # arm64
          - platform: "linux/arm64"
            ruby_version: "2.6.10"
            ruby_major_minor: "2.6"
          - platform: "linux/arm64"
            ruby_version: "2.7.8"
            ruby_major_minor: "2.7"
          - platform: "linux/arm64"
            ruby_version: "3.0.7"
            ruby_major_minor: "3.0"
          - platform: "linux/arm64"
            ruby_version: "3.1.6"
            ruby_major_minor: "3.1"
          - platform: "linux/arm64"
            ruby_version: "3.2.7"
            ruby_major_minor: "3.2"
          - platform: "linux/arm64"
            ruby_version: "3.3.7"
            ruby_major_minor: "3.3"
          - platform: "linux/arm64"
            ruby_version: "3.4.2"
            ruby_major_minor: "3.4"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/${{ github.repository_owner }}/ruby-distroless:${{ matrix.ruby_version }}-${{ matrix.platform }}
          build-args: |
            RUBY_VERSION=${{ matrix.ruby_version }}
            RUBY_MAJOR_MINOR=${{ matrix.ruby_major_minor }}
            LIB_Z_PATH=${{ matrix.platform == 'linux/arm64' ? '/lib/aarch64-linux-gnu/libz.so.1' : '/usr/lib/x86_64-linux-gnu/libz.so.1' }}
            LIB_GMP_PATH=${{ matrix.platform == 'linux/arm64' ? '/usr/lib/aarch64-linux-gnu/libgmp.so.10' : '/usr/lib/x86_64-linux-gnu/libgmp.so.10' }}
            LIB_CRYPT_PATH=${{ matrix.platform == 'linux/arm64' ? '/lib/aarch64-linux-gnu/libcrypt.so.1' : '/lib/x86_64-linux-gnu/libcrypt.so.1' }}
            LIB_GCC_PATH=${{ matrix.platform == 'linux/arm64' ? '/lib/aarch64-linux-gnu/libgcc_s.so.1' : '/usr/lib/x86_64-linux-gnu/libgcc_s.so.1' }}
            LD_LIB_PATH=${{ matrix.platform == 'linux/arm64' ? '/usr/local/lib:/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu' : '/usr/local/lib:/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu' }}
          push: true
